# Use the Node.js version suited for your project (here using Node.js 20)
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and lock files to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose port 3000
EXPOSE 3000


# Run the Next.js app in development mode with hot reloading
CMD ["npm", "run", "dev"]